name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: cybranex/momifa-vf
        build-args: |
          PAYLOAD_CONFIG_PATH=${{secrets.PAYLOAD_CONFIG_PATH}}
          DATABASE_URI=${{secrets.DATABASE_URI}}
          PAYLOAD_SECRET=${{secrets.PAYLOAD_SECRET}}
          STRIPE_SECRET_KEY=${{secrets.STRIPE_SECRET_KEY}}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}}
          OPENCAGE_API_KEY=${{secrets.OPENCAGE_API_KEY}}
          PAYLOAD_PUBLIC_SERVER_URL=${{secrets.PAYLOAD_PUBLIC_SERVER_URL}}
          NEXT_PUBLIC_SERVER_URL=${{secrets.NEXT_PUBLIC_SERVER_URL}}
          NODE_ENV=${{secrets.NODE_ENV}}
